function G = clippedPebi2DGmsh(resGridSize, pdims, faceConstraints)
% Construct a clipped Pebi grid, using Gmsh to generate nodes
% 
% SYNOPSIS:
%   G = clippedPebi2DGmsh(resGridSize, pdims, faceConstraints);
%
% PARAMETERS
%   resGridSize     - Size of the reservoir grid cells, in units of meters.
%
%   pdims           - Vector, length 2, [xmax, ymax], of physical size in
%                     units of meters of the computational domain
%
%   faceConstrants  - A struct of vectors. Each vector, size nf x 2, is the
%                     coordinates of a surface-trace. The surface is
%                     assumed to be linear between the coordinates. The
%                     function will place sites such that the surface is
%                     traced by faces of the grid.

pyDims = py.list(pdims);

py.pebi_grid_2D.pebi_grid_2D( ...
    cell_dimensions=resGridSize, ...
    size=pyDims, ...
    face_constraints=faceConstraints ...
);

if isfile('TEMP_Gmsh_MRST.m')
    pyG = gmshToMRST('TEMP_Gmsh_MRST.m');

    bnd = [
        0 0;
        pdims(1) 0;
        pdims(1) pdims(2);
        0 pdims(2);
    ];

    % clippedPebi2D assumes P is an array of Voronoi sites, while 
    % pyG.nodes.coords is an array of Delaunay sites. As such, we must
    % convert pyG.nodes.coords to Voronoi sites
    sites = voronoin(pyG.nodes.coords);

    % voronoin returns an array of Voronoi sites, but with [Inf, Inf] as
    % the first row. We therefore start at row 2.
    G = clippedPebi2D(sites(2:end, :), bnd);
    delete TEMP_Gmsh_MRST.m
else
    error("No file 'TEMP_Gmsh_MRST.m' generated by python call")
end

end