resGridSize = 0.3;
domain = [1 1];

cellConstraints = {
    [0.1 0.1; 0.9 0.9]
};

G = pebiGrid2DGmshBase( ...
    resGridSize, ...
    domain, ...
    'convertToPEBI', false, ...
    'cellConstraintPerpendicularFactor', 0.5, ...
    'cellConstraints', cellConstraints ...
);
% Plot result
axis off; hold on;
plotGrid(G, 'faceColor', 'none');
for i = 1:length(cellConstraints)
    plot(cellConstraints{i}(:, 1), cellConstraints{i}(:, 2), LineStyle="--", Color="magenta");
end
% Save plot
exportgraphics(gcf,'plots/cell_constraint_as_transfinite_delaunay_1.png')

clf;

G = pebiGrid2DGmshBase( ...
    resGridSize, ...
    domain, ...
    'convertToPEBI', true, ...
    'cellConstraintPerpendicularFactor', 1, ...
    'cellConstraints', cellConstraints ...
);
% Plot result
axis off; hold on;
plotGrid(G, 'faceColor', 'none');
for i = 1:length(cellConstraints)
    plot(cellConstraints{i}(:, 1), cellConstraints{i}(:, 2), LineStyle="--", Color="magenta");
end
% Save plot
exportgraphics(gcf,'plots/cell_constraint_as_transfinite_PEBI_1.png')

clf;
G = pebiGrid2DGmshBase( ...
    resGridSize, ...
    domain, ...
    'convertToPEBI', false, ...
    'cellConstraintPerpendicularCells', int8(5), ...
    'cellConstraintPerpendicularFactor', 1, ...
    'cellConstraints', cellConstraints ...
);
% Plot result
axis off; hold on;
plotGrid(G, 'faceColor', 'none');
for i = 1:length(cellConstraints)
    plot(cellConstraints{i}(:, 1), cellConstraints{i}(:, 2), LineStyle="--", Color="magenta");
end
% Save plot
exportgraphics(gcf,'plots/cell_constraint_as_transfinite_delaunay_2.png')

clf;
G = pebiGrid2DGmshBase( ...
    resGridSize, ...
    domain, ...
    'convertToPEBI', true, ...
    'cellConstraintPerpendicularCells', int8(5), ...
    'cellConstraintPerpendicularFactor', 1, ...
    'cellConstraints', cellConstraints ...
);
% Plot result
axis off; hold on;
plotGrid(G, 'faceColor', 'none');
for i = 1:length(cellConstraints)
    plot(cellConstraints{i}(:, 1), cellConstraints{i}(:, 2), LineStyle="--", Color="magenta");
end
% Save plot
exportgraphics(gcf,'plots/cell_constraint_as_transfinite_pebi_2.png')
